
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DCHANNEL_User_Patient
{

    public int Patient_ID { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> Join_date { get; set; }

    public Nullable<System.DateTime> Last_Login { get; set; }

    public string Patient_Name { get; set; }

    public Nullable<System.DateTime> Birth_Date { get; set; }

    public string Birth_Place { get; set; }

    public string ID_Card_Number { get; set; }

    public string Telp_Number { get; set; }

    public string Status { get; set; }

    public int User_Id { get; set; }

    public string generated_guid { get; set; }

    public string Sex { get; set; }

    public string Current_City { get; set; }

    public string Current_Address { get; set; }

    public string description { get; set; }

    public string Profile_Pic_Url { get; set; }

    public Nullable<System.DateTime> Last_Edited { get; set; }

}

}
