
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STEPPY_API_m_country
{

    public STEPPY_API_m_country()
    {

        this.STEPPY_API_m_user = new HashSet<STEPPY_API_m_user>();

    }


    public int id_country { get; set; }

    public string country_name { get; set; }

    public string country_phone_prefix { get; set; }



    public virtual ICollection<STEPPY_API_m_user> STEPPY_API_m_user { get; set; }

}

}
