
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STEPPY_API_m_contact
{

    public int id_contact { get; set; }

    public string telp_number { get; set; }

    public Nullable<int> id_user { get; set; }

    public Nullable<bool> is_registered { get; set; }



    public virtual STEPPY_API_m_user STEPPY_API_m_user { get; set; }

}

}
