
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STEPPY_API_t_measurement
{

    public long id_measurement { get; set; }

    public Nullable<decimal> value { get; set; }

    public Nullable<long> timestamp { get; set; }

    public Nullable<int> id_measurement_type { get; set; }

    public Nullable<int> id_user { get; set; }

    public Nullable<long> insert_time { get; set; }



    public virtual STEPPY_API_m_measurement_type STEPPY_API_m_measurement_type { get; set; }

    public virtual STEPPY_API_m_user STEPPY_API_m_user { get; set; }

}

}
