

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class STEPPY_APIContainer : DbContext
{
    public STEPPY_APIContainer()
        : base("name=STEPPY_APIContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<STEPPY_API_m_contact> STEPPY_API_m_contact { get; set; }

    public DbSet<STEPPY_API_m_measurement_type> STEPPY_API_m_measurement_type { get; set; }

    public DbSet<STEPPY_API_m_user> STEPPY_API_m_user { get; set; }

    public DbSet<STEPPY_API_t_security_token> STEPPY_API_t_security_token { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

    public DbSet<STEPPY_API_v_user_friend> STEPPY_API_v_user_friend { get; set; }

    public DbSet<STEPPY_API_m_country> STEPPY_API_m_country { get; set; }

    public DbSet<STEPPY_API_t_user_profile> STEPPY_API_t_user_profile { get; set; }

    public DbSet<STEPPY_API_t_measurement> STEPPY_API_t_measurement { get; set; }

    public DbSet<UserProfile> UserProfiles { get; set; }

    public DbSet<webpages_Membership> webpages_Membership { get; set; }

    public DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }

    public DbSet<DCHANNEL_User_Patient> DCHANNEL_User_Patient { get; set; }

    public DbSet<STEPPY_API_BAND_Heartrate> STEPPY_API_BAND_Heartrate { get; set; }

    public DbSet<STEPPY_API_BAND_Step> STEPPY_API_BAND_Step { get; set; }

    public DbSet<STEPPY_Gamification_Mission> STEPPY_Gamification_Mission { get; set; }

    public DbSet<STEPPY_Gamification_Record> STEPPY_Gamification_Record { get; set; }

    public DbSet<STEPPY_new_record> STEPPY_new_record { get; set; }

}

}

