
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class STEPPY_Gamification_Mission
{

    public int IdLevel { get; set; }

    public Nullable<long> Mission1 { get; set; }

    public Nullable<decimal> Mission2 { get; set; }

    public Nullable<long> Mission3 { get; set; }

    public Nullable<decimal> Mission4 { get; set; }

}

}
