
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SteppyNetAPI.WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserProfile
{

    public int UserId { get; set; }

    public string UserName { get; set; }

    public string NoTelp { get; set; }

    public Nullable<int> Umur { get; set; }

    public Nullable<int> Tinggi { get; set; }

    public Nullable<int> BeratBadan { get; set; }

    public string JenisKelamin { get; set; }

    public string Profesi { get; set; }

    public Nullable<System.DateTime> TglLahir { get; set; }

    public string NamaDepan { get; set; }

}

}
