//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteppyNetAPI.WebAPI.Models.OpenMeasurement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenMeasurementConnection : DbContext
    {
        public OpenMeasurementConnection()
            : base("name=OpenMeasurementConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<STEPPY_API_t_loose_measurement> STEPPY_API_t_loose_measurement { get; set; }
    }
}
